# Este arquivo YAML define um grupo chamado "all", que contém um subgrupo chamado "terraform-ansible". O subgrupo "terraform-ansible" contém um host chamado "52.73.70.160".

all:
  # O grupo "all" é o grupo principal e contém todos os hosts.
  hosts:
    terraform-ansible:
      # O grupo "terraform-ansible" contém todos os hosts que executam Terraform.
      - 52.73.70.160
      # O host "52.73.70.160" é o primeiro host do grupo "terraform-ansible".
