---
# Este playbook Ansible executa duas tarefas em todos os hosts do grupo "terraform-ansible":
#
# * Altera o conteúdo do arquivo `index.html` no diretório `/home/ubuntu` para o seguinte:
#
# ```html
# <h1>Feito com terraform e ansible, zona de test</h1>
# ```
#
# * Cria um diretório chamado `Test0` no diretório `/home/ubuntu`.

- hosts: terraform-ansible
  # O grupo "terraform-ansible" contém todos os hosts que executam Terraform.

  tasks:
    # Altera o conteúdo do arquivo `index.html` no diretório `/home/ubuntu`.
    - name: Alterando arquivo.
      copy:
        dest: /home/ubuntu/index.html
        content: "<h1>Feito com terraform e ansible, zona de test</h1>"
      # O arquivo `index.html` é um arquivo HTML que será alterado.
      # O conteúdo do arquivo será alterado para o texto especificado.

    # Cria um diretório chamado `Test0` no diretório `/home/ubuntu`.
    - name: Criando um diretório Test0
      shell: "mkdir Test0"
      # O diretório `Test0` será criado no diretório `/home/ubuntu`.
